### ISSUE TITLE
Config option to don't clear shell output

### ISSUE THREAD

**Issue by yuki-93** [badeball/karma-jsdom-launcher#33]
Hey, 
when I run karma with jsdom as browser, it clears the shell output. It looks like the jsdom-launcher or jsdom clears the shell. Is it possible to switch this generally of or providing a config option for my karma config file. 
Thanks

**Comment by badeball** [comment]
Hello, @yuki-93 

Since 3.0.0, Karma will attempt to [clear the console](https://github.com/karma-runner/karma/blob/v3.0.0/client/karma.js#L223) of any content. When running Karma with jsdom, this will essentially clear your screen, as per [node's spec](https://nodejs.org/api/console.html#console_console_clear). You can avoid this yourself by removing the "clear" property on console for the duration of your tests, as shown [here](https://github.com/badeball/karma-jsdom-launcher/blob/v7.1.1/test/test-helper/index.js#L24) [3].

I will see if I can add this as a configurable option.

**Comment by vediga** [comment]
Im facing the same issue with my angular app, tried removing 'clear' property as suggested in test.ts but it doesn't seem to be working. Did you add any config option for the same?

**Comment by badeball** [comment]
Hi, @vediga. I've changed the default behavior to provide a non-clearing virtual console to JSDOM by default, to avoid this issue. I believe this is the least surprising behavior to users and that few will miss it. It's published as v8.0.0.
